// Enhanced Reminder Interface
export interface Reminder {
  id: string;
  title: string;
  description: string;
  type: 'expense' | 'income' | 'budget' | 'goal' | 'payment' | 'general';
  date: Date;
  time: string;
  isEnabled: boolean;
  repeat: 'none' | 'daily' | 'weekly' | 'monthly';
  category?: string;
  amount?: number;
  
  // New fields for recurring payments
  paymentTemplateId?: string;      // Link to payment template
  isAutoGenerated: boolean;        // System-generated vs manual
  dueDate: Date;                   // Actual due date
  reminderType: 'due' | 'overdue' | 'upcoming'; // Reminder urgency
  originalAmount: number;          // Original payment amount
  createdAt: Date;
  updatedAt: Date;
}

